@startuml

package "Controller"{
    class Formatter
    class CSVController
}

package "Model"{
    class CSVReader
    class Config
    interface ImpConfig
    interface ImpCSVReader

}

package View{
    class CSVWriter
    interface ImpCSVWriter
}

class Config{
    year int
    months []int
    filename []string
    EndOfTheMonthIs30(month int) bool
}

interface ImpConfig{
    GetDirName()
    GetFileName()
}

class CSVReader{
    GetData() [][]string
    ReadFile(filepath) *os.File
    parseCSV ()[][]string
    removeHead(int n, file *os.File)
}

interface ImpCSVReader{
    GetData(filepath)[][]string

}

class CSVController{
    Run()
}

class Formatter{
    FormatData(*data)
    GetAve() *time.Time
    GetAveAfter() *time.Time
    GetAvePreviousFile() *time.Time
}

class CSVWriter{
    Write()
}

interface ImpCSVWriter{
    OverWriteFile(filepath, data)
    MakeDir(dirpath, dirname)

}

CSVReader -|> ImpCSVReader
Config -|> ImpConfig

CSVController -> ImpConfig
CSVController -> ImpCSVReader
CSVController -> Formatter
CSVController -> ImpCSVWriter

CSVWriter -|> ImpCSVWriter

@enduml

