@startuml

package "Controller"{
    class Formatter
    class CSVController
}

package "Model"{
    class CSVReader
    class Config
    interface ImpConfig
    interface ImpReader

}

package View{
    class CSVWriter
    interface ImpWriter
}

class Config{
    year int
    months []int
    filename []string
    EndOfTheMonthIs30(month int) bool
}

interface ImpConfig{
    GetDirName()[]string
    GetFileName()[][]string
}

class CSVReader{
    GetData(filepath string)([][]string, error)
    ReadFile(filepath) *os.File
    parseCSV ()[][]string
    removeHead(n int, file *csv.Reader) error
}

interface ImpReader{
    GetData(filepath)[][]string

}

class CSVController{
    Run()
}

class Formatter{
    Average *time.Time
    AveragePreviousFile *time.Time
    FormatData(data []string)[]string
    GetAve() *time.Time
    GetAveAfter() *time.Time
    GetAvePreviousFile() *time.Time
    SetAve(time *time.Time)
    SetAvePreviousFile(time *time.Time)
}

class CSVWriter{
    Write()
}

interface ImpWriter{
    OverWriteFile(filepath, data)
    MakeDir(dirpath, dirname)

}

CSVReader -|> ImpReader
Config -|> ImpConfig

CSVController -> ImpConfig
CSVController -> ImpReader
CSVController -> Formatter
CSVController -> ImpWriter

CSVWriter -|> ImpWriter

@enduml

