@startuml
participant OldFile
participant Controller
participant Model
participant View
participant NewFile

Controller -> Controller : init
Controller -> Model : init
Controller -> View : init

Controller -> Model : GetDirName()
Controller -> Model : GetFileName()
loop number of files
    Controller -> Model : GetData(filepath)
    Model -> OldFile : Read()
    Model -> Model : ParseCSV
    Controller -> Controller : FormatData()
    Controller -> View : OverWriteFile()
    View -> NewFile : Write()
end


@enduml
